name: Jest and Linting
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependendencies
        run: npm install

      - name: Running Jest Tests
        run: npm test --ci

      - name: Running ESLint
        run: npm run lint
